### ISSUE TITLE
can u tell me how to get the loss function as u write in the code if the approximation network is parameterized in a guassian family?

### ISSUE THREAD

**Issue by Georgehappy1** [Linear95/CLUB#1]

**Comment by Linear95** [comment]
Hi, I have provided a detailed derivation of CLUB under the Gaussian setup in our paper (https://arxiv.org/abs/2006.12013), which needs some time to update on ArXiv. 

Here I attach a screenshot of the equations. Hope it can help to understand the code.
![Screen Shot 2020-07-23 at 6 36 31 PM](https://user-images.githubusercontent.com/30513356/88345452-f6635880-cd13-11ea-81c8-73d6f1f58055.png)

**Comment by Linear95** [comment]
Besides, if you set the variance of the Gaussian distribution to be 1., then the positive and negative terms in CLUB will become two MSE losses. Actually we have tried this and found the performance not very satisfying. Hope this helps :)

**Comment by Georgehappy1** [comment]
thank u so much
