### ISSUE TITLE
Equation issue in mi_minimization.ipynb

### ISSUE THREAD

**Issue by Wolfybox** [Linear95/CLUB#13]
Thanks for your great work in MI estimation!
I was trying to understand and run the mi_minimization.ipynb, but had some doubts about the given equation right at the beginning.
By matrix multiplication, with S =
![image](https://user-images.githubusercontent.com/32531785/140047090-75083883-c4c5-4dc8-b8b8-8b3a671722d0.png),
shouldn't the 
![image](https://user-images.githubusercontent.com/32531785/140047254-2e7f386a-5f17-4993-bdea-ad22c9f1ed51.png) produce 
[ 1, 0,]
[  0, 1]
, which is non-parametric?
How exactly is 
![image](https://user-images.githubusercontent.com/32531785/140047418-bb522005-b3bd-41cc-89af-84bd5aa5396d.png)
being produced by this?
I might have misunderstood this equation.
Could you provide any clues?

**Comment by Linear95** [comment]
Sorry about the confusion. It was actually a typo in the notebook. If you take a look at the code, the matrix s is implemented as
```
s = [ cos(\theta) sin(\theta)
        sin(\theta)  cos(\theta)]
```
I have fixed this typo in the notebook. Thank you for pointing it out!

**Comment by Wolfybox** [comment]
> Sorry about the confusion. It was actually a typo in the notebook. If you take a look at the code, the matrix s is implemented as
> 
> ```
> s = [ cos(\theta) sin(\theta)
>         sin(\theta)  cos(\theta)]
> ```
> 
> I have fixed this typo in the notebook. Thank you for pointing it out!

Thx for the reply. Now it makes a lot more sense.
