### ISSUE TITLE
I want to apppy the mutual imformation to learn the disentangled latent codes.  But if there are four latent codes, how to minimize the objective I(X1; X2; X3; X4)? 

### ISSUE THREAD

**Issue by pandsia2007** [Linear95/CLUB#21]

**Comment by Linear95** [comment]
Good question. You can check another paper of us, which estimated and optimized correlation among multiple variables: [Estimating Total Correlation with Mutual Information Estimators](https://arxiv.org/abs/2011.04794). The code is available [here](https://github.com/Linear95/TC-estimation)

**Comment by pandsia2007** [comment]
> Good question. You can check another paper of us, which estimated and optimized correlation among multiple variables: [Estimating Total Correlation with Mutual Information Estimators](https://arxiv.org/abs/2011.04794). The code is available [here](https://github.com/Linear95/TC-estimation)

Thanks for your great work!
