### ISSUE TITLE
Target Acc only achieves 0.79 for Domain Adaptation experiment on dataset Mnist to MnistM.

### ISSUE THREAD

**Issue by lcd21** [Linear95/CLUB#3]
Thanks for your paper and code, which are really enlightening and helpful. We test the MI_DA code on dataset Mnist to MnistM, however, the mi_loss did not decrease at all and the best acc on target  only achieved 0.79.  Since the 7700 iter, the acc on target did not increase any more.
We used the following commond:
python main_DANN.py --data_path /path/to/data_folder/ --save_path /path/to/save_dir/ --source mnist --target mnistn
and mnistm instruction. Why, could you please give some more tips to help ?
some log  as following:
mnist-mnistm_DANN_0.1 iter 5  mi_loss: -0.9424    p_loss:2.5805    p_acc:0.1406    d_loss: 0.1033    d_acc: 0.9922
mnist-mnistm_DANN_0.1 iter 10  mi_loss: -1.4276    p_loss:1.7437    p_acc:0.4688    d_loss: 0.0160    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 15  mi_loss: -0.4924    p_loss:1.1728    p_acc:0.6250    d_loss: 0.0263    d_acc: 0.9922
mnist-mnistm_DANN_0.1 iter 20  mi_loss: -0.4116    p_loss:0.8434    p_acc:0.7969    d_loss: 0.0077    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 25  mi_loss: -0.4137    p_loss:0.6652    p_acc:0.8281    d_loss: 0.0045    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 30  mi_loss: 0.1388    p_loss:0.4122    p_acc:0.9219    d_loss: 0.0025    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 35  mi_loss: -0.3266    p_loss:0.6541    p_acc:0.8438    d_loss: 0.0019    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 40  mi_loss: -0.3420    p_loss:0.3561    p_acc:0.9375    d_loss: 0.0206    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 45  mi_loss: 0.2164    p_loss:0.4421    p_acc:0.8750    d_loss: 0.0063    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 50  mi_loss: 0.1182    p_loss:0.3425    p_acc:0.9062    d_loss: 0.0145    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 55  mi_loss: 0.2110    p_loss:0.2694    p_acc:0.9531    d_loss: 0.0056    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 60  mi_loss: 0.0381    p_loss:0.1792    p_acc:0.9688    d_loss: 0.0045    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 65  mi_loss: 0.0803    p_loss:0.2354    p_acc:0.9219    d_loss: 0.0581    d_acc: 0.9922
mnist-mnistm_DANN_0.1 iter 70  mi_loss: 0.0865    p_loss:0.3442    p_acc:0.8594    d_loss: 0.0034    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 75  mi_loss: 0.0698    p_loss:0.2371    p_acc:0.9062    d_loss: 0.0033    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 80  mi_loss: 0.0388    p_loss:0.1283    p_acc:0.9844    d_loss: 0.0020    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 85  mi_loss: 0.1110    p_loss:0.2033    p_acc:0.9375    d_loss: 0.0011    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 90  mi_loss: 0.3213    p_loss:0.1764    p_acc:0.9688    d_loss: 0.0025    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 95  mi_loss: -0.1905    p_loss:0.2329    p_acc:0.9375    d_loss: 0.0010    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 100  mi_loss: -0.1830    p_loss:0.2695    p_acc:0.9219    d_loss: 0.0007    d_acc: 1.0000
src valid: 0.9604 tgt valid: 0.4618 tgt test: 0.4432 best: 0.4432 
...
mnist-mnistm_DANN_0.1 iter 1005  mi_loss: -0.0052    p_loss:0.0333    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 1010  mi_loss: 0.1306    p_loss:0.0836    p_acc:0.9688    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 1015  mi_loss: 0.2094    p_loss:0.0845    p_acc:0.9688    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 1020  mi_loss: 0.2839    p_loss:0.0486    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 1025  mi_loss: 0.1201    p_loss:0.0662    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 1030  mi_loss: 0.2046    p_loss:0.1356    p_acc:0.9531    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 1035  mi_loss: -0.1627    p_loss:0.0418    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 1040  mi_loss: 0.1611    p_loss:0.0498    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 1045  mi_loss: 0.1236    p_loss:0.0359    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 1050  mi_loss: 0.1721    p_loss:0.0430    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 1055  mi_loss: 0.3918    p_loss:0.1005    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 1060  mi_loss: -0.0353    p_loss:0.1065    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 1065  mi_loss: 0.1441    p_loss:0.1181    p_acc:0.9531    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 1070  mi_loss: -0.5737    p_loss:0.1507    p_acc:0.9531    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 1075  mi_loss: 0.2092    p_loss:0.0518    p_acc:0.9688    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 1080  mi_loss: 0.2084    p_loss:0.1272    p_acc:0.9688    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 1085  mi_loss: -0.1327    p_loss:0.0545    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 1090  mi_loss: -0.1265    p_loss:0.0931    p_acc:0.9531    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 1095  mi_loss: 0.1478    p_loss:0.0519    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 1100  mi_loss: -0.1057    p_loss:0.0659    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
src valid: 0.9864 tgt valid: 0.6650 tgt test: 0.6611 best: 0.6725 
...
mnist-mnistm_DANN_0.1 iter 2005  mi_loss: 0.0830    p_loss:0.0511    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2010  mi_loss: 0.1078    p_loss:0.0347    p_acc:0.9844    d_loss: 0.0001    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2015  mi_loss: 0.0853    p_loss:0.0646    p_acc:0.9688    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2020  mi_loss: 0.0153    p_loss:0.0474    p_acc:0.9688    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2025  mi_loss: -0.0367    p_loss:0.1069    p_acc:0.9531    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2030  mi_loss: -0.0450    p_loss:0.0501    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2035  mi_loss: 0.1163    p_loss:0.0121    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2040  mi_loss: -0.0938    p_loss:0.0082    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2045  mi_loss: 0.1360    p_loss:0.0125    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2050  mi_loss: 0.2207    p_loss:0.0161    p_acc:1.0000    d_loss: 0.0001    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2055  mi_loss: -0.0965    p_loss:0.0149    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2060  mi_loss: 0.0843    p_loss:0.0110    p_acc:1.0000    d_loss: 0.0001    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2065  mi_loss: -0.0486    p_loss:0.0794    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2070  mi_loss: 0.0611    p_loss:0.0556    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2075  mi_loss: 0.0393    p_loss:0.2532    p_acc:0.9219    d_loss: 0.0001    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2080  mi_loss: 0.1374    p_loss:0.0399    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2085  mi_loss: 0.1120    p_loss:0.0161    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2090  mi_loss: 0.1085    p_loss:0.0277    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2095  mi_loss: -0.0497    p_loss:0.0451    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2100  mi_loss: 0.1559    p_loss:0.0184    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
src valid: 0.9908 tgt valid: 0.7214 tgt test: 0.7189 best: 0.7284 
...
mnist-mnistm_DANN_0.1 iter 2905  mi_loss: 0.1074    p_loss:0.0956    p_acc:0.9688    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2910  mi_loss: 0.1063    p_loss:0.0166    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2915  mi_loss: 0.0295    p_loss:0.0335    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2920  mi_loss: -0.0136    p_loss:0.0238    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2925  mi_loss: -0.0305    p_loss:0.0523    p_acc:0.9688    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2930  mi_loss: -0.1295    p_loss:0.0290    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2935  mi_loss: -0.0361    p_loss:0.0067    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2940  mi_loss: 0.0729    p_loss:0.0424    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2945  mi_loss: 0.0316    p_loss:0.0512    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2950  mi_loss: -0.0648    p_loss:0.0263    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2955  mi_loss: -0.1093    p_loss:0.0278    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2960  mi_loss: 0.0914    p_loss:0.0800    p_acc:0.9688    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2965  mi_loss: 0.0647    p_loss:0.0458    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2970  mi_loss: 0.0216    p_loss:0.0295    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2975  mi_loss: 0.0742    p_loss:0.0486    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2980  mi_loss: -0.0668    p_loss:0.0755    p_acc:0.9688    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2985  mi_loss: -0.0981    p_loss:0.0309    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2990  mi_loss: 0.1510    p_loss:0.1314    p_acc:0.9531    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 2995  mi_loss: 0.0648    p_loss:0.0318    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 3000  mi_loss: -0.0805    p_loss:0.0105    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
src valid: 0.9904 tgt valid: 0.7352 tgt test: 0.7315 best: 0.7392 
...
mnist-mnistm_DANN_0.1 iter 5005  mi_loss: 0.0365    p_loss:0.0057    p_acc:1.0000    d_loss: 0.0020    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 5010  mi_loss: 0.1144    p_loss:0.0103    p_acc:1.0000    d_loss: 0.0007    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 5015  mi_loss: 0.0933    p_loss:0.0057    p_acc:1.0000    d_loss: 0.0024    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 5020  mi_loss: 0.1498    p_loss:0.0209    p_acc:0.9844    d_loss: 0.0005    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 5025  mi_loss: -0.0083    p_loss:0.0251    p_acc:0.9844    d_loss: 0.0022    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 5030  mi_loss: 0.0578    p_loss:0.0156    p_acc:1.0000    d_loss: 0.0226    d_acc: 0.9922
mnist-mnistm_DANN_0.1 iter 5035  mi_loss: -0.0284    p_loss:0.0148    p_acc:1.0000    d_loss: 0.0006    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 5040  mi_loss: 0.0945    p_loss:0.0548    p_acc:0.9844    d_loss: 0.0100    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 5045  mi_loss: 0.1155    p_loss:0.0210    p_acc:0.9844    d_loss: 0.0007    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 5050  mi_loss: -0.0337    p_loss:0.0139    p_acc:1.0000    d_loss: 0.0006    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 5055  mi_loss: 0.0090    p_loss:0.0299    p_acc:1.0000    d_loss: 0.0008    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 5060  mi_loss: 0.1848    p_loss:0.0505    p_acc:0.9844    d_loss: 0.0007    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 5065  mi_loss: -0.0112    p_loss:0.0187    p_acc:0.9844    d_loss: 0.0618    d_acc: 0.9844
mnist-mnistm_DANN_0.1 iter 5070  mi_loss: 0.0610    p_loss:0.0212    p_acc:1.0000    d_loss: 0.0148    d_acc: 0.9922
mnist-mnistm_DANN_0.1 iter 5075  mi_loss: 0.0432    p_loss:0.0338    p_acc:0.9844    d_loss: 0.0022    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 5080  mi_loss: -0.0142    p_loss:0.0224    p_acc:0.9844    d_loss: 0.0061    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 5085  mi_loss: 0.0673    p_loss:0.0254    p_acc:0.9844    d_loss: 0.0012    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 5090  mi_loss: -0.0667    p_loss:0.0071    p_acc:1.0000    d_loss: 0.0006    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 5095  mi_loss: 0.0387    p_loss:0.0437    p_acc:0.9844    d_loss: 0.0006    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 5100  mi_loss: -0.0622    p_loss:0.0460    p_acc:0.9844    d_loss: 0.0056    d_acc: 1.0000
src valid: 0.9916 tgt valid: 0.7566 tgt test: 0.7519 best: 0.7639 
...
mnist-mnistm_DANN_0.1 iter 7605  mi_loss: 0.1248    p_loss:0.1195    p_acc:0.9688    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 7610  mi_loss: -0.0163    p_loss:0.0107    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 7615  mi_loss: 0.0306    p_loss:0.0046    p_acc:1.0000    d_loss: 0.0001    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 7620  mi_loss: 0.0334    p_loss:0.0022    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 7625  mi_loss: 0.0361    p_loss:0.0202    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 7630  mi_loss: 0.1049    p_loss:0.0154    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 7635  mi_loss: 0.0222    p_loss:0.0645    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 7640  mi_loss: 0.0745    p_loss:0.0103    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 7645  mi_loss: -0.0437    p_loss:0.0088    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 7650  mi_loss: 0.0109    p_loss:0.0111    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 7655  mi_loss: 0.0242    p_loss:0.0113    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 7660  mi_loss: 0.0371    p_loss:0.0839    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 7665  mi_loss: 0.0469    p_loss:0.0180    p_acc:1.0000    d_loss: 0.0001    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 7670  mi_loss: 0.0002    p_loss:0.0495    p_acc:0.9844    d_loss: 0.0003    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 7675  mi_loss: 0.0007    p_loss:0.0142    p_acc:1.0000    d_loss: 0.0001    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 7680  mi_loss: -0.0140    p_loss:0.0402    p_acc:0.9688    d_loss: 0.0002    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 7685  mi_loss: 0.0904    p_loss:0.0482    p_acc:0.9688    d_loss: 0.0016    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 7690  mi_loss: 0.0314    p_loss:0.0375    p_acc:0.9844    d_loss: 0.0001    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 7695  mi_loss: 0.1335    p_loss:0.0131    p_acc:1.0000    d_loss: 0.0001    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 7700  mi_loss: -0.0124    p_loss:0.0778    p_acc:0.9844    d_loss: 0.0003    d_acc: 1.0000
src valid: 0.9940 tgt valid: 0.7930 tgt test: 0.7907 best: 0.7907 
...
mnist-mnistm_DANN_0.1 iter 10105  mi_loss: 0.0118    p_loss:0.0226    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 10110  mi_loss: 0.0434    p_loss:0.0452    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 10115  mi_loss: 0.0104    p_loss:0.0040    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 10120  mi_loss: 0.0316    p_loss:0.0234    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 10125  mi_loss: 0.1281    p_loss:0.0341    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 10130  mi_loss: -0.0660    p_loss:0.0087    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 10135  mi_loss: -0.0071    p_loss:0.0055    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 10140  mi_loss: -0.0431    p_loss:0.0118    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 10145  mi_loss: -0.0692    p_loss:0.0028    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 10150  mi_loss: 0.0551    p_loss:0.0390    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 10155  mi_loss: 0.0370    p_loss:0.0023    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 10160  mi_loss: 0.1024    p_loss:0.0493    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 10165  mi_loss: -0.0352    p_loss:0.0212    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 10170  mi_loss: -0.0365    p_loss:0.0044    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 10175  mi_loss: 0.0778    p_loss:0.0028    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 10180  mi_loss: 0.0429    p_loss:0.0024    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 10185  mi_loss: -0.0403    p_loss:0.1771    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 10190  mi_loss: -0.0852    p_loss:0.0144    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 10195  mi_loss: -0.0129    p_loss:0.0045    p_acc:1.0000    d_loss: 0.0000    d_acc: 1.0000
mnist-mnistm_DANN_0.1 iter 10200  mi_loss: -0.0011    p_loss:0.0461    p_acc:0.9844    d_loss: 0.0000    d_acc: 1.0000
src valid: 0.9950 tgt valid: 0.7780 tgt test: 0.7763 best: 0.7907 
...

**Comment by sdai654416** [comment]
Hi, can you try changing the club() in https://github.com/Linear95/CLUB/blob/master/MI_DA/MNISTModel_DANN.py#L422 to club_sample() to see if that works. If not, it could be the mnistm data preprocessing issue. Please email the third author from the paper for the dataset. The email address would firstname.lastname@duke.edu. Cheers!
