### ISSUE TITLE
About parameters updating of CLUB-net and other modules

### ISSUE THREAD

**Issue by Wendison** [Linear95/CLUB#4]
Hi, thanks for releasing this wonderful code! I have several questions on how the parameters are updated for CLUB-net and other modules during training. Based on your main_DANN.py, I think the updating order is: (1) CLUB-net parameters are updated first for maximizing log-likelihood of q(y|x); (2) Then the content-encoder/classifier parameters are updated for minimizing the content classification loss and CLUB of mutual information; (3) Domain-encoder/classifier parameters are updated for minimizing the domain classification loss. My questions are: 
(a) At step (1), will the content-encoder/classifier and domain-encoder/classifier parameters be updated?
(b) Will the CLUB-net parameters be updated at the step (2)?
(c) Will the Domain-encoder/classifier parameters be updated at the step (2)?

**Comment by Linear95** [comment]
Hi Wendison, thank you for your questions. (a) The parameters will not be updated when maximizing the loglikelihoods. (b) The parameters of CLUB will be fixed when updating the content encoder and classifier. (c) Yes, actually step (2) and step (3) proceed together, but are seperated from the update of (1). Hope these help:)
