### ISSUE TITLE
confused about logvar

### ISSUE THREAD

**Issue by junkangwu** [Linear95/CLUB#7]
您好，我看您源码中计算loglikelood时，最大化似然函数应该是
`-(mu - y_samples)**2 /logvar.exp()`
而您使用的方式是
`(-(mu - y_samples)**2 /logvar.exp()-logvar)`
我想请问后面添加的logvar的原因是什么呢？由于它训练起来很可能是负数，导致整个loglikelood一直保持负数水平。

**Comment by junkangwu** [comment]
I understand!

**Comment by sun107** [comment]
> 您好，我看您源码中计算loglikelood时，最大化似然函数应该是
> `-(mu - y_samples)**2 /logvar.exp()`
> 而您使用的方式是
> `(-(mu - y_samples)**2 /logvar.exp()-logvar)`
> 我想请问后面添加的logvar的原因是什么呢？由于它训练起来很可能是负数，导致整个loglikelood一直保持负数水平。

您好，能请您解释一下这个问题吗？我也无法理解为什么需要再减去logvar这一项。十分感谢！

**Comment by BlackLM12138** [comment]
> I understand!
 
I still dont konw why. Could you please explain it briefly? Thank you so much.

**Comment by happylufei** [comment]
> 您好，我看您源码中计算loglikelood时，最大化似然函数应该是 `-(mu - y_samples)**2 /logvar.exp()` 而您使用的方式是 `(-(mu - y_samples)**2 /logvar.exp()-logvar)` 我想请问后面添加的logvar的原因是什么呢？由于它训练起来很可能是负数，导致整个loglikelood一直保持负数水平。

请问算出来的结果都是负值，这合理吗？虽然互信息的趋势是对的，此外，有哪个值是可以直接报告为MI的而不是条件熵上界。如果能得到您的回复，万分感谢！

**Comment by Linear95** [comment]
> > 您好，我看您源码中计算loglikelood时，最大化似然函数应该是
> > `-(mu - y_samples)**2 /logvar.exp()`
> > 而您使用的方式是
> > `(-(mu - y_samples)**2 /logvar.exp()-logvar)`
> > 我想请问后面添加的logvar的原因是什么呢？由于它训练起来很可能是负数，导致整个loglikelood一直保持负数水平。
> 
> 您好，能请您解释一下这个问题吗？我也无法理解为什么需要再减去logvar这一项。十分感谢！

因为高斯概率密度函数前面的正则化系数里面也包括方差参数

**Comment by Linear95** [comment]
> > 您好，我看您源码中计算loglikelood时，最大化似然函数应该是 `-(mu - y_samples)**2 /logvar.exp()` 而您使用的方式是 `(-(mu - y_samples)**2 /logvar.exp()-logvar)` 我想请问后面添加的logvar的原因是什么呢？由于它训练起来很可能是负数，导致整个loglikelood一直保持负数水平。
> 
> 请问算出来的结果都是负值，这合理吗？虽然互信息的趋势是对的，此外，有哪个值是可以直接报告为MI的而不是条件熵上界。如果能得到您的回复，万分感谢！



> > 您好，我看您源码中计算loglikelood时，最大化似然函数应该是 `-(mu - y_samples)**2 /logvar.exp()` 而您使用的方式是 `(-(mu - y_samples)**2 /logvar.exp()-logvar)` 我想请问后面添加的logvar的原因是什么呢？由于它训练起来很可能是负数，导致整个loglikelood一直保持负数水平。
> 
> 请问算出来的结果都是负值，这合理吗？虽然互信息的趋势是对的，此外，有哪个值是可以直接报告为MI的而不是条件熵上界。如果能得到您的回复，万分感谢！

没有准确的MI真值计算方法，只能用上下界估计一个范围。MI为负的话说明estimator还没有well-learned，解决方案可以看这里 https://github.com/Linear95/CLUB/issues/17#issuecomment-1327988913
