### ISSUE TITLE
您好！论文中的公式6是不是存在一些错误呀

### ISSUE THREAD

**Issue by eyuansu62** [Linear95/CLUB#8]

**Comment by eyuansu62** [comment]
倒数第二行那个-KL项，貌似缺一个p(x|y)吧

**Comment by Linear95** [comment]
您好，我没太理解您的意思，可以写一下您的详细的推导过程吗？

**Comment by eyuansu62** [comment]
P(x,y) logp(y|x) / p(y)
= p(x,y) log[(y|x) / r(y)] – p(x,y) log[ p(y) / r(y)]
= p(x,y) log[(y|x) / r(y)] – p(x|y) p(y) log[ p(y) / r(y)]
= E( log[(y|x) / r(y)]) - p(x|y) KL(p(y) || r(y))
您好，不知道我这样推对不对

**Comment by Linear95** [comment]
最后一项 ![image](https://user-images.githubusercontent.com/30513356/113918245-2c684000-97b0-11eb-880c-17a809232e94.png)

**Comment by eyuansu62** [comment]
多谢

**Comment by eyuansu62** [comment]
您好，能否在向您请教一些问题。
我看有的论文里，这里依然会写作数学期望的形式，并不会去掉p(y|x)这一项，请问这里面的区别是什么呢？就比如下面的这个



---原始邮件---
发件人: "Pengyu ***@***.***&gt;
发送时间: 2021年4月8日(周四) 凌晨2:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Linear95/CLUB] 您好！论文中的公式6是不是存在一些错误呀 (#8)




 
最后一项

**Comment by eyuansu62** [comment]
您好，能否在向您请教一些问题。
我看有的论文里，这里依然会写作数学期望的形式，并不会去掉p(y|x)这一项，请问这里面的区别是什么呢？就比如下面的这个

**Comment by eyuansu62** [comment]
这个

**Comment by eyuansu62** [comment]
还想再请教您一下，不知道你能否写一下您的推导过程呢？不胜感激

**Comment by Linear95** [comment]
![image](https://user-images.githubusercontent.com/30513356/114051469-1e232e00-985b-11eb-857f-d83e5fe6fb04.png)

**Comment by eyuansu62** [comment]
不好意思，我想问的是最后一行您是怎么推导的呢？

**Comment by Linear95** [comment]
expectation括号里的部分与x无关

**Comment by jiamings** [comment]
KL(p(y) || r(y)) 应该是 E_{p(y)}[\log p(y) - \log r(y)] 吧

**Comment by Linear95** [comment]
哦对，我被题主都搞糊涂了哈

**Comment by eyuansu62** [comment]
我不就是这样写的吗？？

**Comment by Linear95** [comment]
你少了积分号我少了log……
